name: COMM-PROD-003 - Configure Product Variants - Set up product variants for different configurations
description: 'Set up product variants for different configurations (Module: Commerce, Suite: Product Management)'
starting_url: https://[instance].crm.dynamics.com
steps:
- click: Product variants
- click: Generate variants
- select:
    selector: Dimension 1
    option: Color
- comment: Select "Platinum", "Black"
- select:
    selector: Dimension 2
    option: Storage
- comment: Select "256GB", "512GB", "1TB"
- click: Generate
- assert: 6 variants created
- click: Platinum - 512GB
- write:
    selector: Price
    text: '1299.99'
- write:
    selector: On-hand quantity
    text: '50'
- comment: Toggle "Available online" to on
- comment: Upload "surface-platinum-512.jpg"
- click: Save
- comment: Repeat for all variants with different prices
- comment: Set "256GB" variants at "$999.99"
- comment: Set "1TB" variants at "$1599.99"
