name: COMM-STORE-002 - Configure Payment Methods - Set up payment processing for online store
description: 'Set up payment processing for online store (Module: Commerce, Suite: E-Commerce Store Setup)'
starting_url: https://[instance].crm.dynamics.com
steps:
- click: Payment methods
- click: Add
- select:
    selector: Payment method
    option: Credit card
- select:
    selector: Payment connector
    option: Contoso Payments
- write:
    selector: Merchant ID
    text: Test Merchant ID
- write:
    selector: API Key
    text: '***API-KEY***'
- comment: Toggle "Test mode" to on
- comment: Check "Visa"
- comment: Check "Mastercard"
- comment: Check "American Express"
- comment: Check "Discover"
- comment: Toggle "Authorization only" to on
- write:
    selector: Authorization expiry (days)
    text: '7'
- comment: Toggle "Allow partial payments" to off
- click: Save
- click: Add
- select:
    selector: Payment method
    option: PayPal
- write:
    selector: PayPal account
    text: paypal@contoso.com
- comment: Toggle "Express checkout" to on
- click: Save
- assert: Payment methods (2)
