name: COMM-PROD-004 - Cross-sell Configuration - Set up related products and accessories
description: 'Set up related products and accessories (Module: Commerce, Suite: Product Management)'
starting_url: https://[instance].crm.dynamics.com
steps:
- click: Related products
- click: Add cross-sell
- comment: Search for "Surface Pen"
- click: product
- select:
    selector: Relationship type
    option: Accessory
- write:
    selector: Display order
    text: '1'
- click: Add
- comment: Search for "Surface Type Cover"
- click: product
- select:
    selector: Relationship type
    option: Accessory
- write:
    selector: Display order
    text: '2'
- click: Add
- click: Add up-sell
- comment: Search for "Surface Pro 9 for Business"
- select:
    selector: Relationship type
    option: Upgrade
- write:
    selector: Recommendation text
    text: Premium business features
- click: Add
- assert: Related products (3)
