version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    main: ./src/cmd
    binary: api-cli
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.BuildTime={{.Date}}

universal_binaries:
  - replace: true

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - config/config.yaml.example

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

dockers:
  - image_templates:
      - "virtuoso-api-cli:{{ .Version }}-amd64"
      - "virtuoso-api-cli:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "virtuoso-api-cli:{{ .Version }}-arm64"
      - "virtuoso-api-cli:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "virtuoso-api-cli:{{ .Version }}"
    image_templates:
      - "virtuoso-api-cli:{{ .Version }}-amd64"
      - "virtuoso-api-cli:{{ .Version }}-arm64"
  - name_template: "virtuoso-api-cli:latest"
    image_templates:
      - "virtuoso-api-cli:latest-amd64"
      - "virtuoso-api-cli:latest-arm64"

brews:
  - name: virtuoso-api-cli
    repository:
      owner: marklovelady
      name: homebrew-virtuoso-api-cli
    folder: Formula
    homepage: "https://github.com/marklovelady/virtuoso-api-cli-generator"
    description: "CLI tool for Virtuoso API test automation"
    license: "MIT"
    dependencies:
      - name: go
        type: build
    install: |
      bin.install "api-cli"
      (etc/"virtuoso-api-cli").install "config/config.yaml.example" => "config.yaml"
    test: |
      system "#{bin}/api-cli --version"