# Virtuoso API CLI Configuration
# Place in ~/.api-cli/virtuoso-config.yaml or ./virtuoso-config.yaml

# API configuration
api:
  base_url: https://api-app2.virtuoso.qa/api
  auth_token: your-auth-token-here  # Use VIRTUOSO_API_TOKEN env var for security

# Organization settings
organization:
  id: "2242"  # Your organization ID

# Headers for API requests
headers:
  X-Virtuoso-Client-ID: api-cli-generator
  X-Virtuoso-Client-Name: api-cli-generator

# Output formatting
output:
  default_format: human  # Options: json, yaml, human, ai
  verbose: false

# HTTP client settings  
http:
  timeout: 30  # seconds
  retries: 3