# Development overrides for docker-compose.yml
# This file is automatically loaded by docker-compose in development

version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
      target: builder  # Use builder stage for development
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - RELOAD=true  # Enable auto-reload
    volumes:
      - ./api/app:/app/app:rw  # Read-write for development
      - ./api/tests:/app/tests:ro
    command: |
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug

  cli-builder:
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    volumes:
      - .:/build:rw  # Full source for development
      - go-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    command: |
      sh -c "
        # Install air for hot reload
        go install github.com/cosmtrek/air@latest

        # Create air config if not exists
        if [ ! -f .air.toml ]; then
          cat > .air.toml << 'EOF'
        root = "."
        tmp_dir = "tmp"

        [build]
        cmd = "go build -o ./bin/api-cli ./cmd/api-cli"
        bin = "./bin/api-cli"
        full_bin = "./bin/api-cli list-commands"
        include_ext = ["go", "yaml", "yml"]
        exclude_dir = ["bin", "tmp", "vendor", "api", "test-*", "examples"]
        include_dir = ["cmd", "pkg"]
        exclude_file = ["*_test.go"]
        delay = 1000
        stop_on_error = true
        log = "air_errors.log"

        [log]
        time = true

        [color]
        main = "magenta"
        watcher = "cyan"
        build = "yellow"
        runner = "green"
        EOF
        fi

        # Run air for hot reload
        air -c .air.toml
      "

  redis:
    command: redis-server --appendonly yes --loglevel debug

volumes:
  go-build-cache:
    driver: local
