name: COMM-PROD-004 - Cross-sell Configuration - Set up related products and accessories
description: 'Set up related products and accessories (Module: Commerce, Suite: Product Management)'
project: D365 Test Automation
goal: Commerce Tests
journey: Product Management
infrastructure:
  starting_url: https://[instance].crm.dynamics.com
steps:
- type: interact
  command: click
  target: Related products
- type: interact
  command: click
  target: Add cross-sell
- type: interact
  command: click
  target: product
- type: interact
  command: select
  target: Relationship type
  value: Accessory
- type: interact
  command: write
  target: Display order
  value: '1'
- type: interact
  command: click
  target: Add
- type: interact
  command: click
  target: product
- type: interact
  command: select
  target: Relationship type
  value: Accessory
- type: interact
  command: write
  target: Display order
  value: '2'
- type: interact
  command: click
  target: Add
- type: interact
  command: click
  target: Add up-sell
- type: interact
  command: select
  target: Relationship type
  value: Upgrade
- type: interact
  command: write
  target: Recommendation text
  value: Premium business features
- type: interact
  command: click
  target: Add
- type: assert
  command: exists
  target: Related products (3)
