name: COMM-STORE-003 - Shipping Configuration - Configure shipping methods and rates
description: 'Configure shipping methods and rates (Module: Commerce, Suite: E-Commerce Store Setup)'
project: D365 Test Automation
goal: Commerce Tests
journey: E-Commerce Store Setup
infrastructure:
  starting_url: https://[instance].crm.dynamics.com
steps:
- type: interact
  command: click
  target: Delivery modes
- type: interact
  command: click
  target: New
- type: interact
  command: write
  target: Mode of delivery
  value: Standard Shipping
- type: interact
  command: write
  target: Code
  value: STANDARD
- type: interact
  command: select
  target: Delivery time unit
  value: Days
- type: interact
  command: write
  target: Delivery time
  value: 5-7
- type: interact
  command: write
  target: Charges basis
  value: Flat rate
- type: interact
  command: write
  target: Charges
  value: '9.99'
- type: interact
  command: click
  target: Zones
- type: interact
  command: click
  target: Add zone
- type: interact
  command: select
  target: Country
  value: United States
- type: interact
  command: select
  target: State
  value: All states
- type: interact
  command: click
  target: Save
- type: interact
  command: click
  target: New
- type: interact
  command: write
  target: Mode of delivery
  value: Express Shipping
- type: interact
  command: write
  target: Code
  value: EXPRESS
- type: interact
  command: write
  target: Delivery time
  value: 2-3
- type: interact
  command: select
  target: Charges basis
  value: Weight-based
- type: interact
  command: click
  target: Configure rates
- type: interact
  command: click
  target: Save
