apiVersion: v1
kind: ConfigMap
metadata:
  name: virtuoso-api-config
data:
  # Development API Configuration
  API_BASE_URL: "https://api-dev.virtuoso.qa/api"
  API_TIMEOUT: "60s"  # Longer timeout for debugging
  API_MAX_RETRIES: "5"  # More retries in dev

  # Redis Configuration - Local Redis for dev
  REDIS_HOST: "dev-virtuoso-redis"
  REDIS_DB: "15"  # Use different DB for isolation
  REDIS_POOL_SIZE: "5"

  # Debug Logging Configuration
  LOG_LEVEL: "debug"
  LOG_FORMAT: "text"  # Human-readable for dev
  LOG_TIMESTAMP: "true"
  LOG_CALLER: "true"  # Show caller info in dev
  LOG_STACKTRACE: "true"

  # Server Configuration - Relaxed for debugging
  SERVER_READ_TIMEOUT: "300s"
  SERVER_WRITE_TIMEOUT: "300s"
  SERVER_IDLE_TIMEOUT: "600s"

  # Disable Rate Limiting in dev
  RATE_LIMIT_ENABLED: "false"
  RATE_LIMIT_REQUESTS_PER_MINUTE: "1000"
  RATE_LIMIT_BURST: "100"

  # CORS Configuration - Allow all in dev
  CORS_ALLOWED_ORIGINS: "*"
  CORS_ALLOWED_METHODS: "*"
  CORS_ALLOWED_HEADERS: "*"
  CORS_ALLOW_CREDENTIALS: "true"

  # Health Check Configuration
  HEALTH_CHECK_INTERVAL: "60s"
  HEALTH_CHECK_TIMEOUT: "10s"

  # Metrics Configuration
  METRICS_ENABLED: "true"
  METRICS_DETAILED: "true"  # Detailed metrics in dev

  # Feature Flags - Enable all features for testing
  FEATURE_SESSION_MANAGEMENT: "true"
  FEATURE_ASYNC_EXECUTION: "true"
  FEATURE_WEBHOOK_NOTIFICATIONS: "true"
  FEATURE_EXPERIMENTAL: "true"

  # Development-specific settings
  DEV_MODE: "true"
  PROFILING_ENABLED: "true"
  PROFILING_PATH: "/debug/pprof"
  TRACE_ENABLED: "true"
  TRACE_SAMPLING_RATE: "1.0"  # Trace everything in dev
