apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: virtuoso-api-dev

bases:
- ../../base

namePrefix: dev-

commonLabels:
  environment: dev
  app.kubernetes.io/managed-by: kustomize

patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml
- ingress-patch.yaml

# Dev doesn't need PDB since we run minimal replicas
resources:
- |-
  apiVersion: v1
  kind: Namespace
  metadata:
    name: virtuoso-api-dev
    labels:
      environment: dev

# Remove PDB from dev environment
patchesJson6902:
- target:
    kind: PodDisruptionBudget
    name: virtuoso-api-cli
  patch: |-
    - op: remove
      path: /spec/minAvailable
    - op: add
      path: /spec/minAvailable
      value: 0

images:
- name: virtuoso-api-cli
  newTag: dev-latest
