# Virtuoso API CLI - Shared Test Data
# Reusable test data and fixtures for all tests

# Common selectors used across tests
selectors: &common_selectors
  login_form:
    username_field: "input#username"
    password_field: "input#password"
    submit_button: "button[type='submit']"
    error_message: ".error-message"

  navigation:
    main_menu: "nav.main-menu"
    search_box: "input.search"
    logo: "img.logo"
    footer: "footer.site-footer"

  common_elements:
    heading: "h1"
    subheading: "h2"
    paragraph: "p"
    link: "a"
    button: "button"
    input: "input"
    select: "select"
    checkbox: "input[type='checkbox']"
    radio: "input[type='radio']"

# Test URLs for different scenarios
urls: &test_urls
  simple_page: "/test/simple"
  form_page: "/test/forms"
  dynamic_page: "/test/dynamic"
  iframe_page: "/test/iframes"
  dialog_page: "/test/dialogs"
  upload_page: "/test/upload"
  error_404: "/test/404"
  slow_page: "/test/slow?delay=5000"

# XPath expressions for complex selections
xpath_expressions: &xpath_patterns
  by_text: "//button[text()='Submit']"
  by_contains: "//div[contains(@class, 'message')]"
  by_attribute: "//input[@data-test='email-field']"
  complex_path: "//div[@class='container']//ul/li[position()>2]/a"
  following_sibling: "//label[text()='Email']/following-sibling::input"
  ancestor: "//button[@id='submit']/ancestor::form"

# JavaScript snippets for execute command
javascript_snippets: &js_code
  get_title: "return document.title;"
  get_url: "return window.location.href;"
  scroll_to_bottom: "window.scrollTo(0, document.body.scrollHeight);"
  set_cookie: "document.cookie = 'test=value; path=/;';"
  trigger_alert: "alert('Test Alert');"
  console_log: "console.log('Test message from Virtuoso');"
  get_element_text: "return document.querySelector('h1').textContent;"
  check_jquery: "return typeof jQuery !== 'undefined';"

# Variable names for data storage tests
variables: &test_variables
  page_title: "pageTitle"
  user_name: "userName"
  form_data: "formData"
  timestamp: "currentTime"
  element_count: "elementCount"
  is_visible: "isVisible"
  cookie_value: "cookieValue"

# Edge case test values
edge_cases: &edge_values # String boundaries
  empty_string: ""
  single_char: "a"
  max_length_255: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

  # Special characters
  quotes: '"Hello "World""'
  single_quotes: "'Hello 'World''"
  backslashes: "C:\\Users\\Test\\File.txt"
  newlines: "Line 1\nLine 2\nLine 3"
  tabs: "Column1\tColumn2\tColumn3"

  # Unicode and emojis
  unicode_basic: "你好世界" # Hello World in Chinese
  unicode_rtl: "مرحبا بالعالم" # Hello World in Arabic
  emojis: "😀😁😂😃😄"
  zero_width: "Hello​World" # Zero-width space

  # Numbers
  zero: "0"
  negative: "-12345"
  decimal: "3.14159"
  scientific: "1.23e-4"
  large_number: "9999999999999999"

  # Coordinates
  origin: "0,0"
  negative_coords: "-10,-10"
  large_coords: "9999,9999"
  decimal_coords: "123.45,678.90"

# Cookie test data
cookies: &test_cookies
  session:
    name: "sessionId"
    value: "abc123xyz789"
    domain: ".example.com"
    path: "/"
    expires: "3600"
    secure: true
    httpOnly: true

  preferences:
    name: "userPrefs"
    value: '{"theme":"dark","lang":"en"}'
    path: "/"

  tracking:
    name: "_ga"
    value: "GA1.2.123456789.1234567890"
    expires: "63072000" # 2 years

# Dialog test messages
dialog_messages: &dialog_texts
  alerts:
    - "Operation completed successfully!"
    - "Warning: This action cannot be undone."
    - "Error: Invalid input detected."

  confirms:
    - "Are you sure you want to delete this item?"
    - "Do you want to save your changes?"
    - "Continue with checkout?"

  prompts:
    - "Please enter your name:"
    - "What is your favorite color?"
    - "Enter the verification code:"

# File upload URLs
upload_urls: &file_urls
  image_png: "https://via.placeholder.com/150/0000FF/FFFFFF.png"
  image_jpg: "https://via.placeholder.com/300/FF0000/FFFFFF.jpg"
  document_pdf: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf"
  text_file: "https://raw.githubusercontent.com/virtuoso/test-files/main/sample.txt"
  large_file: "https://speed.hetzner.de/100MB.bin"

# Wait timeouts (milliseconds)
timeouts: &wait_times
  instant: 0
  very_short: 100
  short: 500
  medium: 1000
  long: 5000
  very_long: 10000
  extreme: 30000

# Window dimensions
window_sizes: &dimensions # Mobile devices
  iphone_se: "375x667"
  iphone_12: "390x844"
  pixel_5: "393x851"

  # Tablets
  ipad_mini: "768x1024"
  ipad_pro: "1024x1366"
  surface: "912x1368"

  # Desktop
  laptop: "1366x768"
  desktop_hd: "1920x1080"
  desktop_4k: "3840x2160"

  # Edge cases
  minimum: "320x480"
  maximum: "7680x4320"
  square: "1000x1000"
  portrait: "800x1200"
  landscape: "1200x800"

# Regex patterns for matches assertion
regex_patterns: &regex_tests
  email: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
  phone: "^\\+?1?\\d{9,15}$"
  url: "^https?://[\\w\\-]+(\\.[\\w\\-]+)+[/#?]?.*$"
  ipv4: "^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$"
  uuid: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
  date_iso: "^\\d{4}-\\d{2}-\\d{2}$"
  time_24h: "^([01]?[0-9]|2[0-3]):[0-5][0-9]$"
  alphanumeric: "^[a-zA-Z0-9]+$"
  whitespace: "\\s+"
  html_tag: "<[^>]+>"
