# Virtuoso API CLI Configuration Example
# Copy this file to ~/.api-cli/virtuoso-config.yaml for local development
# This file will be auto-populated with your values during deployment

# API Configuration
api:
  # Your Virtuoso API authentication token
  auth_token: YOUR_VIRTUOSO_API_TOKEN_HERE

  # Virtuoso API base URL
  base_url: https://api-app2.virtuoso.qa/api

  # Request timeout in seconds
  timeout: 30

  # Number of retry attempts for failed requests
  retry_attempts: 3

  # Delay between retries in milliseconds
  retry_delay: 1000

# Organization Configuration
organization:
  # Your Virtuoso organization ID
  id: "2242"

  # Optional: Organization name for display
  name: "Your Organization Name"

# CLI Configuration
cli:
  # Output format preferences
  output:
    # Default format: json, yaml, human, ai
    format: human

    # Pretty print JSON output
    pretty: true

    # Include timestamps in output
    timestamps: false

  # Session management
  session:
    # Enable session context (via VIRTUOSO_SESSION_ID)
    enabled: true

    # Auto-save session state
    auto_save: true

    # Session timeout in minutes
    timeout: 60

  # Command behavior
  commands:
    # Auto-increment position for sequential commands
    auto_position: true

    # Confirm before destructive operations
    confirm_destructive: true

    # Show progress for long operations
    show_progress: true

# Development Configuration
development:
  # Enable debug mode
  debug: false

  # Log API requests and responses
  log_api_calls: false

  # Save API responses for debugging
  save_responses: false

  # Response cache directory
  cache_dir: ~/.api-cli/cache

# Advanced Configuration
advanced:
  # HTTP client settings
  http:
    # Use HTTP/2
    use_http2: true

    # Connection pooling
    max_idle_conns: 100
    idle_conn_timeout: 90

    # TLS configuration
    tls:
      # Skip certificate verification (NOT RECOMMENDED)
      insecure_skip_verify: false

      # Minimum TLS version
      min_version: "1.2"

  # Performance tuning
  performance:
    # Maximum concurrent API requests
    max_concurrent_requests: 10

    # Request rate limiting (requests per second)
    rate_limit: 100

    # Enable request batching
    batch_requests: true

    # Batch size
    batch_size: 50

# Environment-specific overrides
environments:
  # Production environment (default)
  production:
    api:
      base_url: https://api-app2.virtuoso.qa/api
    cli:
      output:
        format: json
      commands:
        confirm_destructive: true

  # Development environment
  development:
    api:
      base_url: https://api-dev.virtuoso.qa/api
    development:
      debug: true
      log_api_calls: true

  # Testing environment
  testing:
    api:
      base_url: https://api-test.virtuoso.qa/api
      timeout: 60
    cli:
      commands:
        confirm_destructive: false

# Feature flags
features:
  # Enable experimental features
  experimental:
    # New test runner
    new_test_runner: false

    # Parallel execution
    parallel_execution: false

    # AI-powered test generation
    ai_test_generation: false

# Deployment information (auto-populated)
deployment:
  # GCP project ID
  project_id: YOUR_PROJECT_ID

  # Cloud Run service URL
  service_url: https://your-service-url.run.app

  # Deployment region
  region: us-central1

  # Deployment timestamp
  deployed_at: 2024-01-01T00:00:00Z
