apiVersion: v1
kind: ConfigMap
metadata:
  name: virtuoso-api-config
data:
  # Staging API Configuration
  API_BASE_URL: "https://api-staging.virtuoso.qa/api"
  API_TIMEOUT: "45s"
  API_MAX_RETRIES: "4"

  # Redis Configuration
  REDIS_HOST: "staging-virtuoso-redis"
  REDIS_DB: "1"
  REDIS_POOL_SIZE: "15"

  # Info Level Logging
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  LOG_TIMESTAMP: "true"
  LOG_CALLER: "false"
  LOG_SAMPLE_RATE: "0.1"  # Sample 10% of info logs

  # Server Configuration
  SERVER_READ_TIMEOUT: "60s"
  SERVER_WRITE_TIMEOUT: "60s"
  SERVER_IDLE_TIMEOUT: "180s"

  # Relaxed Rate Limiting for staging
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS_PER_MINUTE: "120"
  RATE_LIMIT_BURST: "20"

  # CORS Configuration - Staging domains
  CORS_ALLOWED_ORIGINS: "https://*.staging.virtuoso.qa,https://staging.virtuoso.qa"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOWED_HEADERS: "Authorization,Content-Type,X-Request-ID"
  CORS_ALLOW_CREDENTIALS: "true"

  # Health Check Configuration
  HEALTH_CHECK_INTERVAL: "45s"
  HEALTH_CHECK_TIMEOUT: "8s"

  # Metrics Configuration
  METRICS_ENABLED: "true"
  METRICS_DETAILED: "false"

  # Feature Flags - Test new features
  FEATURE_SESSION_MANAGEMENT: "true"
  FEATURE_ASYNC_EXECUTION: "true"
  FEATURE_WEBHOOK_NOTIFICATIONS: "true"
  FEATURE_CANARY: "true"

  # Staging-specific settings
  STAGING_MODE: "true"
  ERROR_STACK_TRACES: "true"
  REQUEST_ID_HEADER: "X-Request-ID"
  TRACE_ENABLED: "true"
  TRACE_SAMPLING_RATE: "0.1"  # Sample 10% of requests
