apiVersion: v2
name: virtuoso-api-cli
description: A Helm chart for Virtuoso API CLI - AI-friendly interface for Virtuoso's test automation platform
type: application
version: 0.1.0
appVersion: "4.1"
keywords:
  - virtuoso
  - api
  - cli
  - test-automation
  - go
home: https://github.com/virtuoso/virtuoso-api-cli
sources:
  - https://github.com/virtuoso/virtuoso-api-cli
maintainers:
  - name: Virtuoso Team
    email: support@virtuoso.qa
icon: https://virtuoso.qa/favicon.ico
annotations:
  # Support for artifact hub
  artifacthub.io/category: testing
  artifacthub.io/license: Apache-2.0
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/signKey: |
    fingerprint: virtuoso-signing-key
    url: https://virtuoso.qa/pgp
  # Chart documentation
  artifacthub.io/changes: |
    - Add initial Helm chart for Virtuoso API CLI
    - Support for multiple environments
    - External secrets integration
    - Redis session management
    - Comprehensive monitoring setup
dependencies:
  - name: redis
    version: "19.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
    tags:
      - session-store
