# Example values for virtuoso-api-cli Helm chart
# This is an example file showing common configuration options

# Basic configuration - REQUIRED
secret:
  apiToken: "your-virtuoso-api-token-here"

config:
  organization:
    id: "2242"  # Your Virtuoso organization ID

# Image configuration
image:
  repository: your-registry.io/virtuoso-api-cli
  tag: "v4.1.0"
  pullPolicy: IfNotPresent

# Enable ingress for external access
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: api-cli.your-domain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: virtuoso-api-cli-tls
      hosts:
        - api-cli.your-domain.com

# Resource configuration for production
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# Enable autoscaling
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

# Enable monitoring
serviceMonitor:
  enabled: true
  labels:
    prometheus: kube-prometheus

# Enable alerts
prometheusRule:
  enabled: true
  labels:
    prometheus: kube-prometheus

# Network policies for security
networkPolicy:
  enabled: true

# Use external secrets for sensitive data
externalSecrets:
  enabled: true
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - secretKey: api-token
      remoteRef:
        key: virtuoso/api-cli
        property: token

# Redis configuration
redis:
  enabled: true
  auth:
    password: "secure-redis-password"
  master:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: fast-ssd

# Custom environment variables
extraEnvVars:
  - name: LOG_LEVEL
    value: "debug"
  - name: CUSTOM_CONFIG
    value: "value"

# Node affinity for production workloads
nodeSelector:
  workload-type: production

# Tolerations for dedicated nodes
tolerations:
  - key: "production-only"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
