project: 9369
goal: 14145
name: COMM-STORE-003 - Shipping Configuration - Configure shipping methods and rates
description: 'Configure shipping methods and rates (Module: Commerce, Suite: E-Commerce Store Setup)'
starting_url: https://virtuoso-test.crm.dynamics.com
steps:
- click: Delivery modes
- click: New
- write:
    selector: Mode of delivery
    text: Standard Shipping
- write:
    selector: Code
    text: STANDARD
- select:
    selector: Delivery time unit
    option: Days
- write:
    selector: Delivery time
    text: 5-7
- write:
    selector: Charges basis
    text: Flat rate
- write:
    selector: Charges
    text: '9.99'
- click: Zones
- click: Add zone
- select:
    selector: Country
    option: United States
- select:
    selector: State
    option: All states
- click: Save
- click: New
- write:
    selector: Mode of delivery
    text: Express Shipping
- write:
    selector: Code
    text: EXPRESS
- write:
    selector: Delivery time
    text: 2-3
- select:
    selector: Charges basis
    option: Weight-based
- click: Configure rates
- comment: Add tier "0-5 lbs" with rate "19.99"
- comment: Add tier "5-10 lbs" with rate "29.99"
- comment: Add tier "10+ lbs" with rate "39.99"
- click: Save
