name: MARKET-JOURNEY-002 - Configure Journey Settings - Set journey parameters and goals
description: 'Set journey parameters and goals (Module: Marketing, Suite: Customer Journeys)'
project: D365 Test Automation
goal: Marketing Tests
journey: Customer Journeys
infrastructure:
  starting_url: https://[instance].crm.dynamics.com
steps:
- type: interact
  command: click
  target: General
- type: interact
  command: select
  target: Target
  value: Marketing segment
- type: interact
  command: select
  target: Segment
  value: New Customers This Month
- type: interact
  command: write
  target: Start date
  value: $TODAY
- type: interact
  command: write
  target: End date
  value: $DATE_PLUS_30
- type: interact
  command: select
  target: Start time
  value: Immediate
- type: interact
  command: click
  target: Goals
- type: interact
  command: click
  target: Add goal
- type: interact
  command: select
  target: Goal type
  value: Email clicked
- type: interact
  command: write
  target: Target percentage
  value: '20'
- type: interact
  command: click
  target: Save
- type: interact
  command: click
  target: Schedule
- type: interact
  command: select
  target: Contact frequency
  value: Allow re-entry
- type: interact
  command: write
  target: Days between re-entry
  value: '7'
- type: interact
  command: select
  target: Execution schedule
  value: Business days only
- type: interact
  command: click
  target: Exit conditions
- type: interact
  command: click
  target: Add condition
- type: interact
  command: select
  target: Condition
  value: Unsubscribed
- type: interact
  command: click
  target: Save
