# API CLI Generator Configuration
# This file contains the configuration for the API CLI

api:
  base_url: https://api.example.com/api
  auth_token: your-auth-token-here
  
organization:
  id: "your-org-id"
  
headers:
  X-Client-ID: api-cli-generator
  X-Client-Name: api-cli-generator
  
# Business rules
business_rules:
  initial_checkpoint_name: "INITIAL_CHECKPOINT"
  auto_attach_checkpoints: true
  create_initial_journey: true
  
# Output formatting
output:
  default_format: human  # Options: json, yaml, human, ai
  verbose: false
  
# HTTP client settings
http:
  timeout: 30  # seconds
  retries: 3
  retry_wait: 1  # seconds
  
# Logging
logging:
  level: info  # Options: debug, info, warn, error
  file: ~/.api-cli/api-cli.log

# Session context management
session:
  # Current project context
  current_project_id: null
  current_goal_id: null
  current_snapshot_id: null
  current_journey_id: null
  current_checkpoint_id: null
  
  # Position management
  auto_increment_position: true
  next_position: 1
