api:
  base_url: https://api-app2.virtuoso.qa/api
  auth_token: test-token
  
organization:
  id: "2242"
  
headers:
  X-Virtuoso-Client-ID: api-cli-generator
  X-Virtuoso-Client-Name: api-cli-generator
  
business_rules:
  initial_checkpoint_name: "INITIAL_CHECKPOINT"
  auto_attach_checkpoints: true
  create_initial_journey: true
  
output:
  default_format: human
  verbose: false
  
http:
  timeout: 30
  retries: 3
  retry_wait: 1
  
logging:
  level: info
  file: ~/.api-cli/api-cli.log

session:
  current_project_id: null
  current_goal_id: null
  current_snapshot_id: null
  current_journey_id: null
  current_checkpoint_id: 1678318
  auto_increment_position: true
  next_position: 3