api:
    auth_token: test-token
    base_url: https://api-app2.virtuoso.qa/api
business_rules:
    auto_attach_checkpoints: true
    create_initial_journey: true
    initial_checkpoint_name: INITIAL_CHECKPOINT
headers:
    x-virtuoso-client-id: api-cli-generator
    x-virtuoso-client-name: api-cli-generator
http:
    retries: 3
    retry_wait: 1
    timeout: 30
logging:
    file: ~/.api-cli/api-cli.log
    level: info
organization:
    id: "2242"
output:
    default_format: human
    verbose: false
session:
    auto_increment_position: true
    current_checkpoint_id: 1680450
    current_goal_id: null
    current_journey_id: null
    current_project_id: null
    current_snapshot_id: null
    next_position: 47
