apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: virtuoso-api-cli
  namespace: virtuoso-api
  labels:
    app: virtuoso-api-cli
    component: api
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: virtuoso-api-cli
      component: api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    metricRelabelings:
    # Drop high cardinality metrics
    - sourceLabels: [__name__]
      regex: '(go_memstats_alloc_bytes_total|go_memstats_sys_bytes|go_memstats_mallocs_total|go_memstats_frees_total)'
      action: drop
    # Keep only important metrics
    - sourceLabels: [__name__]
      regex: '(virtuoso_api_.*|http_.*|process_.*|go_gc_.*)'
      action: keep
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: virtuoso-redis
  namespace: virtuoso-api
  labels:
    app: virtuoso-api-cli
    component: redis
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: virtuoso-api-cli
      component: redis
  endpoints:
  - port: redis-exporter
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    scheme: http
    metricRelabelings:
    # Keep only important Redis metrics
    - sourceLabels: [__name__]
      regex: '(redis_up|redis_connected_clients|redis_commands_processed_total|redis_keyspace_.*|redis_memory_.*|redis_latency_.*)'
      action: keep
