apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: virtuoso-api

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pdb.yaml
  - networkpolicy.yaml
  # Monitoring resources
  - monitoring/servicemonitor.yaml
  - monitoring/prometheusrule.yaml
  - monitoring/grafana-dashboard.yaml
  # Job resources
  - jobs/backup-cronjob.yaml
  - jobs/cleanup-cronjob.yaml
  - jobs/health-check-cronjob.yaml

commonLabels:
  app.kubernetes.io/name: virtuoso-api-cli
  app.kubernetes.io/instance: production
  app.kubernetes.io/component: api
  app.kubernetes.io/part-of: virtuoso
  app.kubernetes.io/managed-by: kustomize
