apiVersion: v1
kind: Secret
metadata:
  name: virtuoso-api-secret
  namespace: virtuoso-api
  labels:
    app: virtuoso-api-cli
    component: secret
type: Opaque
stringData:
  # Virtuoso API Credentials
  # IMPORTANT: Replace these placeholder values with actual credentials
  VIRTUOSO_API_KEY: "YOUR_VIRTUOSO_API_KEY_HERE"
  VIRTUOSO_AUTH_TOKEN: "YOUR_VIRTUOSO_AUTH_TOKEN_HERE"
  VIRTUOSO_ORGANIZATION_ID: "YOUR_ORGANIZATION_ID_HERE"

  # Redis Password
  REDIS_PASSWORD: "YOUR_REDIS_PASSWORD_HERE"

  # API Secret Keys
  JWT_SECRET: "YOUR_JWT_SECRET_HERE"
  ENCRYPTION_KEY: "YOUR_ENCRYPTION_KEY_HERE"

  # Webhook Secret (if using webhooks)
  WEBHOOK_SECRET: "YOUR_WEBHOOK_SECRET_HERE"

  # External Service Keys (if needed)
  SLACK_WEBHOOK_URL: ""
  DATADOG_API_KEY: ""

  # Database Connection (if using external DB)
  DATABASE_URL: ""
