# Development environment substitutions for Cloud Build
# These values override defaults in cloudbuild.yaml

substitutions:
  _ENVIRONMENT: 'dev'
  _REGION: 'us-central1'
  _SERVICE_NAME: 'virtuoso-api-cli-dev'
  _ARTIFACT_REGISTRY: 'virtuoso-artifacts-dev'
  _ENABLE_APPROVAL: 'false'
  _MAX_INSTANCES: '50'
  _MIN_INSTANCES: '0'
  _MEMORY: '256Mi'
  _CPU: '1'
  _TIMEOUT: '300'

  # Database settings
  _DB_TIER: 'db-f1-micro'
  _DB_BACKUP_ENABLED: 'false'
  _DB_HIGH_AVAILABILITY: 'false'

  # Monitoring settings
  _ALERT_ENABLED: 'false'
  _LOG_RETENTION_DAYS: '7'

  # Testing settings
  _RUN_INTEGRATION_TESTS: 'true'
  _RUN_PERFORMANCE_TESTS: 'false'
  _RUN_SECURITY_SCAN: 'true'

  # Feature flags
  _ENABLE_DEBUG: 'true'
  _ENABLE_PROFILING: 'true'
  _ENABLE_TRACING: 'true'

  # API settings
  _API_RATE_LIMIT: '1000'
  _API_TIMEOUT: '30s'
  _API_MAX_CONNECTIONS: '100'

  # Storage settings
  _BACKUP_RETENTION_DAYS: '7'
  _LOG_STORAGE_CLASS: 'STANDARD'

  # Notification settings
  _NOTIFY_ON_SUCCESS: 'false'
  _NOTIFY_ON_FAILURE: 'true'
  _NOTIFICATION_CHANNEL: 'dev-alerts'

# Environment-specific configuration
options:
  machineType: 'E2_STANDARD_2'
  diskSizeGb: 50
  logging: CLOUD_LOGGING_ONLY

# Development-specific timeout (shorter for faster feedback)
timeout: 1200s
