# Production environment substitutions for Cloud Build
# These values override defaults in cloudbuild.yaml

substitutions:
  _ENVIRONMENT: 'prod'
  _REGION: 'us-central1'
  _SERVICE_NAME: 'virtuoso-api-cli'
  _ARTIFACT_REGISTRY: 'virtuoso-artifacts'
  _ENABLE_APPROVAL: 'true'
  _MAX_INSTANCES: '100'
  _MIN_INSTANCES: '3'
  _MEMORY: '1Gi'
  _CPU: '2'
  _TIMEOUT: '300'

  # Multi-region configuration
  _SECONDARY_REGION: 'us-east1'
  _ENABLE_MULTI_REGION: 'true'

  # Database settings
  _DB_TIER: 'db-n1-standard-2'
  _DB_BACKUP_ENABLED: 'true'
  _DB_HIGH_AVAILABILITY: 'true'
  _DB_BACKUP_TIME: '03:00'
  _DB_BACKUP_LOCATION: 'us'
  _DB_POINT_IN_TIME_RECOVERY: 'true'

  # Monitoring settings
  _ALERT_ENABLED: 'true'
  _LOG_RETENTION_DAYS: '90'
  _ALERT_THRESHOLD_ERROR_RATE: '1'
  _ALERT_THRESHOLD_LATENCY: '500'
  _ENABLE_APM: 'true'
  _ENABLE_ERROR_REPORTING: 'true'

  # Testing settings
  _RUN_INTEGRATION_TESTS: 'true'
  _RUN_PERFORMANCE_TESTS: 'true'
  _RUN_SECURITY_SCAN: 'true'
  _RUN_SMOKE_TESTS: 'true'
  _RUN_CANARY_ANALYSIS: 'true'

  # Feature flags
  _ENABLE_DEBUG: 'false'
  _ENABLE_PROFILING: 'false'
  _ENABLE_TRACING: 'true'
  _ENABLE_METRICS: 'true'
  _ENABLE_AUDIT_LOGGING: 'true'

  # API settings
  _API_RATE_LIMIT: '10000'
  _API_TIMEOUT: '90s'
  _API_MAX_CONNECTIONS: '1000'
  _ENABLE_API_KEY_ROTATION: 'true'

  # Storage settings
  _BACKUP_RETENTION_DAYS: '90'
  _LOG_STORAGE_CLASS: 'COLDLINE'
  _ENABLE_OBJECT_LIFECYCLE: 'true'

  # Notification settings
  _NOTIFY_ON_SUCCESS: 'true'
  _NOTIFY_ON_FAILURE: 'true'
  _NOTIFICATION_CHANNEL: 'prod-alerts'
  _PAGE_ON_FAILURE: 'true'
  _ESCALATION_POLICY: 'oncall-sre'

  # Blue-green deployment settings
  _TRAFFIC_SPLIT_INITIAL: '5'
  _TRAFFIC_SPLIT_INTERVAL: '300' # 5 minutes
  _ROLLBACK_ON_ERROR: 'true'
  _CANARY_DURATION: '1800' # 30 minutes

  # Security settings
  _ENABLE_WAF: 'true'
  _ENABLE_DDOS_PROTECTION: 'true'
  _SSL_POLICY: 'MODERN'
  _ENABLE_PRIVATE_IP: 'true'

  # Compliance settings
  _ENABLE_DATA_ENCRYPTION: 'true'
  _ENCRYPTION_KEY: 'projects/${PROJECT_ID}/locations/global/keyRings/virtuoso/cryptoKeys/api-key'
  _ENABLE_ACCESS_LOGGING: 'true'
  _COMPLIANCE_MODE: 'SOC2'

# Environment-specific configuration
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 200
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'production-pool'

# Production timeout (longer for safety)
timeout: 3600s
