# Staging environment substitutions for Cloud Build
# These values override defaults in cloudbuild.yaml

substitutions:
  _ENVIRONMENT: 'staging'
  _REGION: 'us-central1'
  _SERVICE_NAME: 'virtuoso-api-cli-staging'
  _ARTIFACT_REGISTRY: 'virtuoso-artifacts'
  _ENABLE_APPROVAL: 'false'
  _MAX_INSTANCES: '75'
  _MIN_INSTANCES: '1'
  _MEMORY: '512Mi'
  _CPU: '1'
  _TIMEOUT: '300'

  # Database settings
  _DB_TIER: 'db-g1-small'
  _DB_BACKUP_ENABLED: 'true'
  _DB_HIGH_AVAILABILITY: 'false'
  _DB_BACKUP_TIME: '02:00'

  # Monitoring settings
  _ALERT_ENABLED: 'true'
  _LOG_RETENTION_DAYS: '30'
  _ALERT_THRESHOLD_ERROR_RATE: '5'
  _ALERT_THRESHOLD_LATENCY: '1000'

  # Testing settings
  _RUN_INTEGRATION_TESTS: 'true'
  _RUN_PERFORMANCE_TESTS: 'true'
  _RUN_SECURITY_SCAN: 'true'
  _RUN_SMOKE_TESTS: 'true'

  # Feature flags
  _ENABLE_DEBUG: 'false'
  _ENABLE_PROFILING: 'true'
  _ENABLE_TRACING: 'true'
  _ENABLE_METRICS: 'true'

  # API settings
  _API_RATE_LIMIT: '5000'
  _API_TIMEOUT: '60s'
  _API_MAX_CONNECTIONS: '500'

  # Storage settings
  _BACKUP_RETENTION_DAYS: '30'
  _LOG_STORAGE_CLASS: 'NEARLINE'

  # Notification settings
  _NOTIFY_ON_SUCCESS: 'true'
  _NOTIFY_ON_FAILURE: 'true'
  _NOTIFICATION_CHANNEL: 'staging-alerts'

  # Blue-green deployment settings
  _TRAFFIC_SPLIT_INITIAL: '10'
  _TRAFFIC_SPLIT_INTERVAL: '60' # seconds
  _ROLLBACK_ON_ERROR: 'true'

# Environment-specific configuration
options:
  machineType: 'E2_HIGHCPU_4'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

# Staging timeout
timeout: 2400s
