apiVersion: v1
kind: ConfigMap
metadata:
  name: virtuoso-api-config
data:
  # Production API Configuration
  API_BASE_URL: "https://api-app2.virtuoso.qa/api"
  API_TIMEOUT: "30s"
  API_MAX_RETRIES: "3"
  API_CIRCUIT_BREAKER: "true"
  API_CIRCUIT_BREAKER_THRESHOLD: "5"

  # Redis Configuration - Production cluster
  REDIS_HOST: "virtuoso-redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_POOL_SIZE: "25"
  REDIS_MAX_RETRIES: "3"
  REDIS_SENTINEL_ENABLED: "true"
  REDIS_SENTINEL_MASTER: "mymaster"
  REDIS_SENTINELS: "redis-sentinel-0:26379,redis-sentinel-1:26379,redis-sentinel-2:26379"

  # Structured JSON Logging for production
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  LOG_TIMESTAMP: "true"
  LOG_CALLER: "false"
  LOG_SAMPLING: "true"
  LOG_SAMPLE_RATE: "0.01"  # Sample 1% of info logs
  LOG_OUTPUT: "stdout"

  # Server Configuration - Production optimized
  SERVER_READ_TIMEOUT: "30s"
  SERVER_WRITE_TIMEOUT: "30s"
  SERVER_IDLE_TIMEOUT: "120s"
  SERVER_MAX_HEADER_BYTES: "1048576"
  SERVER_KEEP_ALIVE: "true"
  SERVER_KEEP_ALIVE_PERIOD: "90s"

  # Strict Rate Limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS_PER_MINUTE: "60"
  RATE_LIMIT_BURST: "10"
  RATE_LIMIT_STORE: "redis"  # Use Redis for distributed rate limiting

  # CORS Configuration - Production domains only
  CORS_ALLOWED_ORIGINS: "https://app.virtuoso.qa,https://api.virtuoso.qa"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOWED_HEADERS: "Authorization,Content-Type,X-Request-ID,X-API-Key"
  CORS_ALLOW_CREDENTIALS: "false"
  CORS_MAX_AGE: "43200"  # 12 hours

  # Health Check Configuration
  HEALTH_CHECK_INTERVAL: "30s"
  HEALTH_CHECK_TIMEOUT: "5s"
  HEALTH_CHECK_DETAILED: "false"  # Hide details in production

  # Metrics Configuration
  METRICS_ENABLED: "true"
  METRICS_PATH: "/metrics"
  METRICS_AUTH_REQUIRED: "true"
  METRICS_INCLUDE_HOST: "true"
  METRICS_INCLUDE_STATUS_CODE: "true"

  # Feature Flags - Stable features only
  FEATURE_SESSION_MANAGEMENT: "true"
  FEATURE_ASYNC_EXECUTION: "true"
  FEATURE_WEBHOOK_NOTIFICATIONS: "false"
  FEATURE_CIRCUIT_BREAKER: "true"
  FEATURE_REQUEST_CACHING: "true"

  # Production-specific settings
  PRODUCTION_MODE: "true"
  ERROR_EXPOSE_DETAILS: "false"
  REQUEST_ID_HEADER: "X-Request-ID"
  TRACE_ENABLED: "true"
  TRACE_SAMPLING_RATE: "0.001"  # Sample 0.1% of requests
  TRACE_EXPORTER: "jaeger"
  TRACE_ENDPOINT: "http://jaeger-collector:14268/api/traces"

  # Security settings
  SECURITY_HEADERS_ENABLED: "true"
  SECURITY_CSRF_ENABLED: "true"
  SECURITY_API_KEY_ROTATION: "90d"

  # Performance settings
  CACHE_ENABLED: "true"
  CACHE_TTL: "300s"
  COMPRESSION_ENABLED: "true"
  COMPRESSION_LEVEL: "5"
