apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "virtuoso-api-cli.fullname" . }}-config
  labels:
    {{- include "virtuoso-api-cli.labels" . | nindent 4 }}
data:
  # API Configuration
  API_BASE_URL: {{ .Values.config.api.baseUrl | quote }}
  API_TIMEOUT: {{ .Values.config.api.timeout | quote }}
  API_MAX_RETRIES: {{ .Values.config.api.maxRetries | quote }}

  # Organization Configuration
  ORGANIZATION_ID: {{ required "Organization ID is required" .Values.config.organization.id | quote }}

  # Redis Configuration
  REDIS_HOST: {{ include "virtuoso-api-cli.redisHost" . | quote }}
  REDIS_PORT: {{ include "virtuoso-api-cli.redisPort" . | quote }}
  REDIS_DB: {{ .Values.config.redis.db | quote }}
  REDIS_POOL_SIZE: {{ .Values.config.redis.poolSize | quote }}
  REDIS_MAX_RETRIES: {{ .Values.config.redis.maxRetries | quote }}

  # Logging Configuration
  LOG_LEVEL: {{ .Values.config.logging.level | quote }}
  LOG_FORMAT: {{ .Values.config.logging.format | quote }}
  LOG_TIMESTAMP: {{ .Values.config.logging.timestamp | quote }}
  LOG_CALLER: {{ .Values.config.logging.caller | quote }}

  # Server Configuration
  SERVER_READ_TIMEOUT: {{ .Values.config.server.readTimeout | quote }}
  SERVER_WRITE_TIMEOUT: {{ .Values.config.server.writeTimeout | quote }}
  SERVER_IDLE_TIMEOUT: {{ .Values.config.server.idleTimeout | quote }}
  SERVER_MAX_HEADER_BYTES: {{ .Values.config.server.maxHeaderBytes | quote }}

  # Rate Limiting
  RATE_LIMIT_ENABLED: {{ .Values.config.rateLimit.enabled | quote }}
  RATE_LIMIT_REQUESTS_PER_MINUTE: {{ .Values.config.rateLimit.requestsPerMinute | quote }}
  RATE_LIMIT_BURST: {{ .Values.config.rateLimit.burst | quote }}

  # CORS Configuration
  CORS_ALLOWED_ORIGINS: {{ .Values.config.cors.allowedOrigins | quote }}
  CORS_ALLOWED_METHODS: {{ .Values.config.cors.allowedMethods | quote }}
  CORS_ALLOWED_HEADERS: {{ .Values.config.cors.allowedHeaders | quote }}
  CORS_MAX_AGE: {{ .Values.config.cors.maxAge | quote }}

  # Health Check Configuration
  HEALTH_CHECK_INTERVAL: {{ .Values.config.healthCheck.interval | quote }}
  HEALTH_CHECK_TIMEOUT: {{ .Values.config.healthCheck.timeout | quote }}

  # Metrics Configuration
  METRICS_ENABLED: {{ .Values.config.metrics.enabled | quote }}
  METRICS_PATH: {{ .Values.config.metrics.path | quote }}

  # Feature Flags
  FEATURE_SESSION_MANAGEMENT: {{ .Values.config.features.sessionManagement | quote }}
  FEATURE_ASYNC_EXECUTION: {{ .Values.config.features.asyncExecution | quote }}
  FEATURE_WEBHOOK_NOTIFICATIONS: {{ .Values.config.features.webhookNotifications | quote }}

  # Virtuoso CLI config file
  virtuoso-config.yaml: |
    api:
      auth_token: "${API_TOKEN}"
      base_url: {{ .Values.config.api.baseUrl }}
    organization:
      id: {{ .Values.config.organization.id | quote }}
