{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "virtuoso-api-cli.fullname" . }}
  labels:
    {{- include "virtuoso-api-cli.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "virtuoso-api-cli.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from ingress controller
    {{- if .Values.ingress.enabled }}
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingress.namespaceSelector | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.containerPort }}
    {{- end }}
    # Allow traffic from same namespace
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.containerPort }}
    # Allow Prometheus scraping
    {{- if .Values.serviceMonitor.enabled }}
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.metrics.namespaceSelector | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.containerPort }}
    {{- end }}
    {{- with .Values.networkPolicy.ingress.custom }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    # Allow DNS
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
        - podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow access to Kubernetes API
    - to:
        - namespaceSelector: {}
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
    # Allow access to Redis
    {{- if .Values.redis.enabled }}
    - to:
        - podSelector:
            matchLabels:
              {{- include "virtuoso-api-cli.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: redis
      ports:
        - protocol: TCP
          port: 6379
    {{- end }}
    # Allow external HTTPS traffic (for Virtuoso API)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 169.254.169.254/32
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
    {{- with .Values.networkPolicy.egress.custom }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
