{{- if .Values.verticalPodAutoscaler.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "virtuoso-api-cli.fullname" . }}
  labels:
    {{- include "virtuoso-api-cli.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "virtuoso-api-cli.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.verticalPodAutoscaler.updateMode }}
  resourcePolicy:
    containerPolicies:
    - containerName: {{ .Chart.Name }}
      {{- with .Values.verticalPodAutoscaler.controlledResources }}
      controlledResources: {{ . }}
      {{- end }}
      {{- with .Values.verticalPodAutoscaler.maxAllowed }}
      maxAllowed:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.verticalPodAutoscaler.minAllowed }}
      minAllowed:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
