project: 9369
goal: 14138
name: SERVICE-SLA-001 - Configure SLA - Set up new SLA for premium customers
description: 'Set up new SLA for premium customers (Module: Customer Service, Suite: Service Level Agreements)'
starting_url: https://virtuoso-test.crm.dynamics.com
steps:
- click: Service Management
- click: SLAs
- click: New
- write:
    selector: Name
    text: Premium Customer SLA
- select:
    selector: Entity
    option: Case
- write:
    selector: Description
    text: SLA for premium tier customers
- click: New SLA Item
- write:
    selector: Name
    text: First Response
- select:
    selector: KPI Field
    option: First Response By
- select:
    selector: Failure Time
    option: 4 hours
- select:
    selector: Warning Time
    option: 2 hours
- click: Save & Close
- click: Success Conditions
- click: Add Condition
- select:
    selector: Field
    option: Case Status
- select:
    selector: Operator
    option: equals
- select:
    selector: Value
    option: Resolved
- click: Save
