name: Test API Connection

on:
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Test API with curl
        env:
          API_KEY: ${{ secrets.VIRTUOSO_API_KEY }}
          API_URL: ${{ vars.VIRTUOSO_API_URL }}
        run: |
          echo "Testing API connectivity..."

          # Test 1: Basic connectivity without auth
          echo "1. Testing basic connectivity to $API_URL/health"
          curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" "$API_URL/health" || echo "Failed"

          # Test 2: With Bearer token and organizationId
          echo -e "\n2. Testing with Bearer token and organizationId"
          curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" \
            -H "Authorization: Bearer $API_KEY" \
            "$API_URL/projects?organizationId=2242" || echo "Failed"

          # Test 3: With API key header and organizationId
          echo -e "\n3. Testing with X-API-Key header and organizationId"
          curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" \
            -H "X-API-Key: $API_KEY" \
            "$API_URL/projects?organizationId=2242" || echo "Failed"

          # Test 4: List projects with Bearer token and organizationId (full response)
          echo -e "\n4. Getting projects list with Bearer token and organizationId"
          response=$(curl -s -w "\nHTTP_STATUS:%{http_code}" \
            -H "Authorization: Bearer $API_KEY" \
            -H "Content-Type: application/json" \
            "$API_URL/projects?organizationId=2242")

          http_status=$(echo "$response" | grep -o "HTTP_STATUS:[0-9]*" | cut -d: -f2)
          body=$(echo "$response" | sed '$d')

          echo "HTTP Status: $http_status"
          echo "Response body (first 500 chars):"
          echo "$body" | head -c 500

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test config file formats
        env:
          API_KEY: ${{ secrets.VIRTUOSO_API_KEY }}
          API_URL: ${{ vars.VIRTUOSO_API_URL }}
        run: |
          echo -e "\n\nTesting different config file formats..."

          # Test format 1: api_key / api_url
          echo -e "\n5. Testing with api_key/api_url config"
          mkdir -p ~/.api-cli
          cat > ~/.api-cli/config.yaml << EOF
          api_key: $API_KEY
          api_url: $API_URL
          EOF

          echo "Config file 1:"
          cat ~/.api-cli/config.yaml

          # Test format 2: auth_token / base_url with organization
          echo -e "\n6. Testing with auth_token/base_url config"
          cat > ~/.api-cli/virtuoso-config.yaml << EOF
          api:
            auth_token: $API_KEY
            base_url: $API_URL
          organization:
            id: "2242"
          headers:
            X-Virtuoso-Client-ID: "api-cli-generator"
            X-Virtuoso-Client-Name: "api-cli-generator"
          EOF

          echo "Config file 2:"
          cat ~/.api-cli/virtuoso-config.yaml
